name: Deploy Next.js to EC2
on:
  push:
    branches:
      - main
      - staging
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy to EC2
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          # First run a diagnostic to find the correct paths
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            echo 'Finding pnpm and pm2 locations:'
            which pnpm || echo 'pnpm not in PATH'
            which pm2 || echo 'pm2 not in PATH'
            npm list -g | grep pnpm || echo 'pnpm not found in npm global'
            npm list -g | grep pm2 || echo 'pm2 not found in npm global'
          "
          
          # Then run the actual deployment with a login shell to ensure proper environment
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} bash -l -c "
            # Navigate to project directory
            cd ${{ secrets.EC2_PATH }}
            
            # Git operations
            git fetch origin
            git checkout ${BRANCH}
            git pull origin ${BRANCH}
            
            # Build and deploy
            source ~/.bashrc || true
            source ~/.profile || true
            
            # Try different approaches to run pnpm
            echo 'Running with npm global path for pnpm and pm2'
            npm -g exec pnpm install && \\
            npm -g exec pnpm build && \\
            npm -g exec pm2 restart next-app || npm -g exec pm2 start 'npm -g exec pnpm start' --name next-app
          "
