name: Deploy Next.js to EC2
on:
  push:
    branches:
      - main
      - staging
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
      - name: Create Deploy Script
        run: |
          cat << 'EOF' > deploy.sh
          #!/bin/bash
          set -e
          
          # Find Node.js executables
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          
          # Try multiple locations for Node executables
          NODE_PATHS=(
            "$HOME/.nvm/versions/node/*/bin"
            "$HOME/.local/bin"
            "/usr/local/bin"
            "/usr/bin"
            "$HOME/.npm-global/bin"
          )
          
          for path in "${NODE_PATHS[@]}"; do
            if [ -d "$path" ]; then
              export PATH="$path:$PATH"
            fi
          done
          
          # Navigate to project directory
          cd "$1"
          
          # Git operations
          git fetch origin
          git checkout "$2"
          git pull origin "$2"
          
          # Find pnpm and pm2
          PNPM_CMD=$(command -v pnpm || echo "$HOME/.local/share/pnpm/pnpm" || echo "$HOME/node_modules/.bin/pnpm" || echo "npx pnpm")
          PM2_CMD=$(command -v pm2 || echo "$HOME/node_modules/.bin/pm2" || echo "npx pm2")
          
          echo "Using pnpm at: $PNPM_CMD"
          echo "Using pm2 at: $PM2_CMD"
          
          # Install pnpm and pm2 if not available
          if ! command -v pnpm &> /dev/null; then
            echo "Installing pnpm..."
            npm install -g pnpm || npx pnpm@latest -v
          fi
          
          if ! command -v pm2 &> /dev/null; then
            echo "Installing pm2..."
            npm install -g pm2 || npx pm2@latest -v
          fi
          
          # Build and deploy
          echo "Running pnpm install..."
          $PNPM_CMD install || npx pnpm install
          
          echo "Running pnpm build..."
          $PNPM_CMD build || npx pnpm build
          
          echo "Starting/restarting with PM2..."
          $PM2_CMD restart next-app || $PM2_CMD start "npx pnpm start" --name next-app || npx pm2 restart next-app || npx pm2 start "npx pnpm start" --name next-app
          
          echo "Deployment completed successfully!"
          EOF
          
          chmod +x deploy.sh
      
      - name: Copy Deploy Script to Server
        run: |
          scp -i ~/.ssh/id_ed25519 deploy.sh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/deploy.sh
      
      - name: Execute Deploy Script
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "bash ~/deploy.sh ${{ secrets.EC2_PATH }} ${BRANCH} || (echo 'Script failed with status $?'; cat ~/deploy-log.txt)"
